---
# Source: textscope/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pp-textscope
  labels:
    helm.sh/chart: textscope-0.1.0
    app.kubernetes.io/name: textscope
    app.kubernetes.io/instance: pp
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: textscope
      app.kubernetes.io/instance: pp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: textscope
        app.kubernetes.io/instance: pp
    spec:
      serviceAccountName: pp-textscope
      securityContext:
        {}
      containers:
        - name: textscope
          securityContext:
            {}
          image: "docker.lomin.ai/ts-pp:0.6.0"
          imagePullPolicy: Never
          workingDir: /workspace/pp_server
          command: 
            
              - python3
            
              - main.py
            
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
              - name: PYTHONPATH
                value: /workspace
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
          resources:
            {}
          volumeMounts:
            - mountPath: /workspace/logs
              name: log
      volumes:
        - name: log
          hostPath:
            path: /home/inhak/log
            type: DirectoryOrCreate
