FROM nginx:latest

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ARG NGINX_FILE_DEFAULT
ARG NGINX_FILE_NGINX

RUN apt-get -qq update
RUN apt-get -y -qq install locales
RUN locale-gen ko_KR.UTF-8

COPY ./proxy/default.conf /etc/nginx/conf.d/default.conf
COPY ./proxy/nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]