ARG UBUNTU_VERSION


FROM ubuntu:${UBUNTU_VERSION}

ARG POETRY_VERSION
ARG PYTHON_VERSION

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PYTHONPATH="$PYTHONPATH:/workspace"
ENV PATH="/root/.local/bin:${PATH}"
ENV DOCKER_ENV="True"

RUN apt-get -qq update && \
    apt-get -y -qq install locales && \
    locale-gen ko_KR.UTF-8

RUN DEBIAN_FRONTEND="noninteractive" apt-get -y -qq install git \
    python3-pip \
    python3-venv \
    libmysqlclient-dev \
    poppler-utils \
    libldap2-dev \
    libsasl2-dev \
    libssl-dev \
    libgl1-mesa-glx \
    libglib2.0-0 \
    tzdata \
    curl

RUN curl -sSL https://install.python-poetry.org | POETRY_VERSION=${POETRY_VERSION} python3 - && \
    echo "PATH=/root/.local/bin:$PATH" > /etc/environment && \
    poetry config virtualenvs.create false

RUN pip3 install --upgrade pip

WORKDIR /workspace
RUN git clone https://github.com/Nuitka/Nuitka.git && \
    cd Nuitka && \
    python3 setup.py install

COPY ./requirements/web/pyproject.toml /workspace/
COPY ./requirements/web/poetry.lock /workspace/

RUN poetry install

RUN sed -i 's/# Support for gcc and clang, restricting visibility as much as possible./env.Append(CCFLAGS=["-fcf-protection=none"])/' /usr/local/lib/python${PYTHON_VERSION}/dist-packages/nuitka/build/SconsCompilerSettings.py

RUN groupadd -r lomin -g 1000 && \
    useradd -m -u 1000 -r -g lomin -s /sbin/nologin -c "Docker image user" textscope

RUN apt-get -qq update
RUN apt-get -qq install -y software-properties-common
RUN add-apt-repository ppa:libreoffice/ppa

RUN apt-get -qq update
# RUN apt-get -qq install -y libreoffice=1:7.4.2~rc3-0ubuntu0.20.04.1~lo1
RUN apt-get -qq install -y libreoffice

COPY ./assets/fonts/NanumGothic.ttf /home/textscope/.local/share/fonts/NanumGothic.ttf
RUN chown textscope:lomin /home/textscope/.local/share/fonts/NanumGothic.ttf

USER textscope

WORKDIR /workspace/app

ENTRYPOINT ["python3", "main.py"]
