ARG UBUNTU_VERSION=18.04

FROM ubuntu:${UBUNTU_VERSION}

ENV PYTHONPATH="$PYTHONPATH:/workspace"

RUN apt-get update && \
    apt-get -y install git && \
    apt-get -y install python3-pip && \
    apt-get -y install libmysqlclient-dev && \
    apt-get -y install poppler-utils && \
    apt-get -y install python-dev libldap2-dev libsasl2-dev libssl-dev && \
    apt-get -y install libgl1-mesa-glx libglib2.0-0 && \
    DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata

# korean
RUN apt-get install -y apt-utils locales
RUN locale-gen ko_KR.UTF-8
ENV LC_ALL ko_KR.UTF-8

RUN pip3 install --upgrade pip

WORKDIR /workspace
RUN git clone https://github.com/Nuitka/Nuitka.git && \
    cd Nuitka && \
    python3 setup.py install

COPY ./requirments/requirments-web.txt /workspace/requirments-web.txt
RUN pip3 install -r /workspace/requirments-web.txt
