# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an web image
      inputs:
        repository: $(docker.lomin.ai/ts-web:0.0.1)
        command: build
        dockerfile: './Dockerfile.fastapi'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build an serving image
      inputs:
        repository: $(docker.lomin.ai/ts-web:0.0.1)
        command: build
        dockerfile: './Dockerfile.bentoml'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build an postgres image
      inputs:
        repository: $(postgres)
        command: build
        image: postgres:11
        tags: |
          $(tag)
