# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-20.04
    steps:
    - task: Docker@2
      displayName: Build an web image
      inputs:
        # repository: 
        command: build
        dockerfile: './Dockerfile.fastapi'
        tags: |
          $(docker.lomin.ai/ts-web:0.0.1)
    # - task: Docker@2
    #   displayName: Build an serving image
    #   inputs:
    #     # repository: 
    #     command: build
    #     dockerfile: './Dockerfile.bentoml'
    #     tags: |
    #       $(docker.lomin.ai/ts-web:0.0.1)
    - script: |
          pip3 install pytest
          pytest tests
          python -m nuitka --module app --include-package=app
          mv app/main.py ./main.py
          python -m nuitka main.py
          docker-compose up -d
  # ./main.bin
  # - stage: Testing
  #   displayName: Testing web app
  #   jobs:
  #   - job: Build
  #     displayName: Build
  #     pool:
  #       vmImage: ubuntu-latest
  #     steps:

  # - stage: Convert from python to c


  # - task: PublishBuildArtifacts@1