version: "2.3"

services:
  minio:
    container_name: textscope-minio
    image: quay.io/minio/minio:RELEASE.2022-02-24T22-12-01Z
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_API_TRANSITION_WORKERS: ${MINIO_API_TRANSITION_WORKERS}
    ports:
      - 9000:${MINIO_IP_PORT}
      - 9001:9001
    networks:
      - our_net
    volumes:
      - minio_data:/data
    command: minio server /data --console-address "${MINIO_IP_ADDR}:9001"
  postgresql:
    container_name: textscope-postgresql
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 55432:${POSTGRES_IP_PORT}
    networks:
      - our_net

  serving:
    image: docker.lomin.ai/ts-gpu-serving:${TEXTSCOPE_SERVING_VERSION}
    container_name: textscope-serving
    environment:
      - CUSTOMER=${CUSTOMER}
      - TZ=Asia/Seoul
    volumes:
      - ${MOUNT_LOG_PATH}:/workspace/logs
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    runtime: nvidia
    networks:
      - our_net

  web:
    container_name: textscope-web
    image: docker.lomin.ai/ts-web:${TEXTSCOPE_CORE_VERSION}
    environment:
      - CUSTOMER=${CUSTOMER}
      - TZ=Asia/Seoul
    volumes:
      - ${MOUNT_LOG_PATH}:/workspace/logs
    restart: unless-stopped
    depends_on:
      - postgresql
      - minio
    cap_add:
      - SYS_PTRACE
    networks:
      - our_net

  pp:
    container_name: textscope-pp
    image: docker.lomin.ai/ts-pp:${TEXTSCOPE_PP_VERSION}
    environment:
      - CUSTOMER=${CUSTOMER}
      - TZ=Asia/Seoul
    volumes:
      - ${MOUNT_LOG_PATH}:/workspace/logs
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    networks:
      - our_net

  wrapper:
    container_name: textscope-wrapper
    image: docker.lomin.ai/ts-wrapper:${TEXTSCOPE_WRAPPER_VERSION}
    environment:
      - CUSTOMER=${CUSTOMER}
      - TZ=Asia/Seoul
    volumes:
      - ${MOUNT_LOG_PATH}:/workspace/logs
    restart: unless-stopped
    depends_on:
      - postgresql
      - minio
    networks:
      - our_net

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  our_net:
    name: our_net
    ipam:
      config:
        - subnet: 10.254.0.0/16
