version: '2.3'

services:

  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports: 
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      our_net:
          ipv4_address: ${POSTGRES_IP_ADDR}
  
  web:
    image: docker.lomin.ai/ts-server:0.0.1
    container_name: web
    ports: 
      - 8000:8000
    volumes:
      - ./:/workspace
    build:
      context: ./app/utils
      dockerfile: Dockerfile
    tty: true
    depends_on: 
      - postgres
    networks:
      our_net:
          ipv4_address: ${WEB_IP_ADDR}
    restart: unless-stopped

  serving:
    image: docker.lomin.ai/ts-model:0.0.1
    build:
      context: ./app/serving
      dockerfile: Dockerfile.bentoml
    container_name: serving
    ports: 
      - "5000:5000"
    volumes:
      - ./:/workspace
      # - ./app/utils/bentoml_configuration.yml:/user/home/bentoml/bentoml.yml
    depends_on: 
      - postgres
    networks:
      our_net:
          ipv4_address: ${SERVING_IP_ADDR}
    runtime: nvidia
    # command: python /workspace/generate_bentoml_model.py
    tty: true

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #       - pgadmin:/root/.pgadmin
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - postgres
  #   restart: unless-stopped


networks:
  our_net:
    ipam:
      config:
        - subnet: 182.20.0.0/24