version: '2.3'

services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul
  
  serving:
    ports: 
      - 8052:5000
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    tty: true
    depends_on: 
      - mysql
    BENTOML_CONFIG=/workspace/inference_server/assets/bentoml_configuration.yml bentoml serve-gunicorn . --port=5000

  serving_replica:
    tty: true
    depends_on: 
      - mysql
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]
    BENTOML_CONFIG=/workspace/bentoml_textscope/assets/bentoml_configuration.yml bentoml serve-gunicorn . --port=5000

  web:
    volumes:
      - ./logs:/workspace/logs
    tty: true
    depends_on: 
      - mysql
    command: python3 app/main.py

  pp:
    volumes:
      - ./logs:/workspace/logs
    tty: true
    depends_on: 
      - mysql
    command: python3 pp_server/app/main.py

  wrapper:
    ports: 
      - 8050:8090
    volumes:
      - ./logs:/workspace/logs
    tty: true
    command: python3 kakaobank_wrapper/app/main.py

  grafana:
    ports:
      - 8053:3000
    restart: always

  mysql-exporter:
    environment:
      - DATA_SOURCE_NAME=${MYSQL_ROOT_USER}:${MYSQL_PASSWORD}@(${MYSQL_IP_ADDR}:3306)/
    cap_add:
      - SYS_NICE
