version: "2.3"

services:
  serving:
    image: docker.lomin.ai/ts-gpu-serving-build:${TEXTSCOPE_BASE_IMAGE_VERSION}
    container_name: serving
    tty: true
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - CUSTOMER=${CUSTOMER}
    runtime: nvidia
    build:
      context: inference_server
      dockerfile: Dockerfile.build
      args:
        USER: ${USER}
        CUSTOMER: ${CUSTOMER}
        BUNDLE_PATH: ${BUNDLE_PATH}
        PYTHON_VERSION: ${PYTHON_VERSION}
        MODEL_SERVICE: ${MODEL_SERVICE}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        BASE_PATH: ${BASE_PATH}
        LINUX_ENV_PATH: ${LINUX_ENV_PATH}
        DEMOMA_PATH: ${DEMOMA_PATH}
        SO_EXTENTION: ${SO_EXTENTION}
        TEXTSCOPE_BASE_IMAGE_VERSION: ${TEXTSCOPE_BASE_IMAGE_VERSION}

  serving_replica:
    image: docker.lomin.ai/ts-gpu-serving-build:${TEXTSCOPE_BASE_IMAGE_VERSION}
    environment:
      - CUDA_VISIBLE_DEVICES=1
      - CUSTOMER=${CUSTOMER}
    runtime: nvidia

  wrapper:
    image: docker.lomin.ai/ts-wrapper-base:${TEXTSCOPE_BASE_IMAGE_VERSION}
    container_name: wrapper
    environment:
      - CUSTOMER=${CUSTOMER}

  web:
    image: docker.lomin.ai/ts-web-build:${TEXTSCOPE_BASE_IMAGE_VERSION}
    container_name: web
    environment:
      - CUSTOMER=${CUSTOMER}
    build:
      context: ./
      dockerfile: docker/build/Dockerfile.web
      args:
        USER: ${USER}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        BASE_PATH: ${BASE_PATH}
        LINUX_ENV_PATH: ${LINUX_ENV_PATH}
        DEMOMA_PATH: ${DEMOMA_PATH}
        SO_EXTENTION: ${SO_EXTENTION}
        TEXTSCOPE_BASE_IMAGE_VERSION: ${TEXTSCOPE_BASE_IMAGE_VERSION}

  pp:
    image: docker.lomin.ai/ts-pp-build:${TEXTSCOPE_BASE_IMAGE_VERSION}
    container_name: pp
    environment:
      - CUSTOMER=${CUSTOMER}
    build:
      context: ./
      dockerfile: docker/build/Dockerfile.pp
      args:
        USER: ${USER}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        BASE_PATH: ${BASE_PATH}
        LINUX_ENV_PATH: ${LINUX_ENV_PATH}
        DEMOMA_PATH: ${DEMOMA_PATH}
        SO_EXTENTION: ${SO_EXTENTION}
        TEXTSCOPE_BASE_IMAGE_VERSION: ${TEXTSCOPE_BASE_IMAGE_VERSION}
