version: '2.3'

services:

  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports: 
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      our_net:
          ipv4_address: ${POSTGRES_IP_ADDR}
  
  web:
    image: docker.lomin.ai/ts-web:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile.fastapi
    container_name: web
    ports: 
      - 8000:8000
    volumes:
      - ./:/workspace
    tty: true
    depends_on: 
      - postgres
    networks:
      our_net:
          ipv4_address: ${WEB_IP_ADDR}
    restart: unless-stopped
    command: python /workspace/app/main.py

  serving:
    image: docker.lomin.ai/ts-serving:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile.bentoml
    container_name: serving
    ports: 
      - 5000:5000
    volumes:
      - ./:/workspace
      # - ./app/utils/bentoml_configuration.yml:/user/home/bentoml/bentoml.yml
    tty: true
    depends_on: 
      - postgres
    networks:
      our_net:
          ipv4_address: ${SERVING_IP_ADDR}
    runtime: nvidia
    command: bentoml serve MultiModelService:latest

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on: 
      - web
      - serving
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      our_net:
          ipv4_address: ${PROMETHEUS_IP_ADDR}
    restart: always
    

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on: 
      - prometheus
    volumes: 
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      our_net:
          ipv4_address: ${GRAFANA_IP_ADDR}
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
        - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      our_net:
          ipv4_address: ${PGADMIN_IP_ADDR}
    restart: unless-stopped

volumes: 
  prometheus_data: {}
  grafana_data: {}
  pgdata: {}
  pgadmin: {}

networks:
  our_net:
    ipam:
      config:
        - subnet: 182.20.0.0/24
