version: '2.3'

services:
  mysql1:
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul
  
  serving:
    image: docker.lomin.ai/ts-gpu-serving-base:${TEXTSCOPE_BASE_IMAGE_VERSION}
    build:
      context: ./
      dockerfile: docker/base/Dockerfile.gpu_serving
      args:
        USER: ${USER}
        CUSTOMER: ${CUSTOMER}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        PYTHON_VERSION: ${PYTHON_VERSION}
        CUSTOMER: ${CUSTOMER}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

  web:
    image: docker.lomin.ai/ts-web-base:${TEXTSCOPE_BASE_IMAGE_VERSION}
    build:
      context: ./
      dockerfile: docker/base/Dockerfile.web
      args:
        USER: ${USER}
        UBUNTU_VERSION: ${UBUNTU_VERSION}

  pp:
    image: docker.lomin.ai/ts-pp-base:${TEXTSCOPE_BASE_IMAGE_VERSION}
    build:
      context: ./
      dockerfile: docker/base/Dockerfile.pp
      args:
        USER: ${USER}
        UBUNTU_VERSION: ${UBUNTU_VERSION}

  wrapper:
    image: docker.lomin.ai/ts-wrapper-base:${TEXTSCOPE_BASE_IMAGE_VERSION}
    build:
      context: ./
      dockerfile: docker/base/Dockerfile.wrapper
      args:
        USER: ${USER}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        CUSTOMER: ${CUSTOMER}
      