version: '2.3'

services:
  serving:
    build:
      context: inference_server
      dockerfile: ./Dockerfile.production
      args:
        MAINTAINER: ${MAINTAINER}
        APP_NAME: inference_server
        BUILD_FOLDER_PATH: ${BUILD_FOLDER_PATH}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        CUSTOMER: ${CUSTOMER}
        PYTHON_VERSION: ${PYTHON_VERSION}
        TEXTSCOPE_BASE_IMAGE_VERSION: ${TEXTSCOPE_BASE_IMAGE_VERSION}
    ports: 
      - 8052:5000
    environment:
      - DEBUG=/workspace/inference_server/assets/bentoml_configuration.yml
      - CUDA_VISIBLE_DEVICES=0
      - SERVICE_INSTANCE=serving
      - ARTIFACT_NAME_LIST=${ARTIFACT_NAME_LIST}
    runtime: nvidia
    tty: true
    command: bentoml serve textscope_model_service --host 0.0.0.0

  # serving_replica:
  #   tty: true
  #   environment:
  #     - DEBUG=/workspace/inference_server/assets/bentoml_configuration.yml
  #     - CUDA_VISIBLE_DEVICES=1
  #     - SERVICE_INSTANCE=serving_replica
  #   runtime: nvidia
  #   command: bentoml serve-gunicorn /workspace/inference_server/ModelService/ --port=5000 --disable-microbatch --timeout=${MODEL_SERVER_TIMEOUT_SECOND}

  web:
    build:
      context: ./
      dockerfile: docker/production/Dockerfile.web
      args:
        MAINTAINER: ${MAINTAINER}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        BUILD_FOLDER_PATH: ${BUILD_FOLDER_PATH}
        CUSTOMER: ${CUSTOMER}
        TEXTSCOPE_BASE_IMAGE_VERSION: ${TEXTSCOPE_BASE_IMAGE_VERSION}
    tty: true
    working_dir: /workspace
    command: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0:8000
    # command: python3 /workspace/main.py

  pp:
    build:
      context: ./
      dockerfile: docker/production/Dockerfile.pp
      args:
        MAINTAINER: ${MAINTAINER}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        BUILD_FOLDER_PATH: ${BUILD_FOLDER_PATH}
        CUSTOMER: ${CUSTOMER}
        TEXTSCOPE_BASE_IMAGE_VERSION: ${TEXTSCOPE_BASE_IMAGE_VERSION}
    environment:
      - PYTHONPATH=/workspace
    tty: true
    working_dir: /workspace/pp_server
    command: gunicorn main:app -w 9 -k uvicorn.workers.UvicornWorker -b 0:8080
    # command: python3 /workspace/pp_server/main.py

  wrapper:
    build:
      context: ./
      dockerfile: docker/production/Dockerfile.wrapper
      args:
        MAINTAINER: ${MAINTAINER}
        CUSTOMER: ${CUSTOMER}
        BUILD_FOLDER_PATH: ${BUILD_FOLDER_PATH}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        TEXTSCOPE_BASE_IMAGE_VERSION: ${TEXTSCOPE_BASE_IMAGE_VERSION}
    ports: 
      - 8050:8090
    tty: true
    volumes:
      - ./${CUSTOMER}_wrapper:/workspace/${CUSTOMER}_wrapper
    working_dir: /workspace/${CUSTOMER}_wrapper/${CUSTOMER}_wrapper/app
    command: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0:8090
    # command: python3 /workspace/${CUSTOMER}_wrapper/${CUSTOMER}_wrapper/app/main.py

  grafana:
    ports:
      - 8053:3000