version: '2.3'

services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul
  
  serving:
    build:
      context: ./
      dockerfile: docker/production/Dockerfile.gpu_serving
      args:
        APP_NAME: inference_server
        BUILD_FOLDER_PATH: ${BUILD_FOLDER_PATH}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        CUSTOMER: ${CUSTOMER}
        PYTHON_VERSION: ${PYTHON_VERSION}
    ports: 
      - 8052:5000
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    tty: true
    volumes:
      - ./others/assets/tiff_register:/workspace/others/assets/tiff_register/

    depends_on: 
      - mysql
    # command: BENTOML_CONFIG=/workspace/inference_server/assets/bentoml_configuration.yml bentoml serve-gunicorn /workspace/inference_server/ModelService/ --port=5000
    # command: bentoml serve-gunicorn /workspace/inference_server/ModelService/ --port=5000

  # serving_replica:
  #   tty: true
  #   depends_on: 
  #     - mysql
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           device_ids: ['1']
  #           capabilities: [gpu]
  #   depends_on: 
  #   - mysql
  #   # command: BENTOML_CONFIG=/workspace/inference_server/assets/bentoml_configuration.yml bentoml serve-gunicorn /workspace/inference_server/ModelService/ --port=5000
  #   # command: bentoml serve-gunicorn /workspace/inference_server/ModelService/ --port=5000

  web:
    build:
      context: ./
      dockerfile: docker/production/Dockerfile.web
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        BUILD_FOLDER_PATH: ${BUILD_FOLDER_PATH}
    volumes:
      - ./logs:/workspace/logs
    tty: true
    depends_on: 
      - mysql
    command: python3 /workspace/main.py

  pp:
    build:
      context: ./
      dockerfile: docker/production/Dockerfile.pp
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        BUILD_FOLDER_PATH: ${BUILD_FOLDER_PATH}
    volumes:
      - ./logs:/workspace/logs
    tty: true
    depends_on: 
      - mysql
    command: python3 /workspace/pp_server/main.py

  wrapper:
    build:
      context: ./
      dockerfile: docker/production/Dockerfile.wrapper
      args:
        CUSTOMER: ${CUSTOMER}
        BUILD_FOLDER_PATH: ${BUILD_FOLDER_PATH}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
    ports: 
      - 8050:8090
    volumes:
      - ./logs:/workspace/logs
      - ./:/workspace
      - ./others/assets/tiff_register:/workspace/others/assets/tiff_register/
    tty: true
    # command: python3 /workspace/${CUSTOMER}_wrapper/main.py

  grafana:
    ports:
      - 8053:3000
    restart: always

  mysql-exporter:
    environment:
      - DATA_SOURCE_NAME=${MYSQL_ROOT_USER}:${MYSQL_PASSWORD}@(${MYSQL_IP_ADDR}:3306)/
    cap_add:
      - SYS_NICE
