FROM python:3.7

RUN pip3 install fastapi uvicorn

# EXPOSE 80

RUN apt-get update && \
    apt-get install sudo && \
    apt-get install nano && \
    apt-get install git

# RUN sudo apt-get -y install postgresql postgresql-contrib
RUN sudo apt-get -y install postgresql-client

RUN pip3 install --pre -U bentoml 

RUN git clone http://github.com/bentoml/bentoml && \
    cd bentoml && \
    pip3 install jupyter && \
    pip3 install -r ./guides/quick-start/requirements.txt

RUN pip3 install python-jose[cryptography] && \
    pip3 install passlib[bcrypt] && \
    pip3 install python-multipart && \
    pip3 install cryptography==3.3.2

RUN pip3 install psycopg2-binary && \
    pip3 install python-dotenv && \
    pip3 install pydantic[email] && \
    pip3 install PyJWT

RUN pip3 install fastapi_profiler && \
    pip3 install fastapi-cprofile && \ 
    pip3 install pyinstrument_flame && \
    pip3 install prometheusrock && \
    pip3 install loguru

RUN apt-get install -y psmisc

RUN pip3 install opencv-python && \
    apt-get -y install libgl1-mesa-glx

WORKDIR /
RUN git clone https://github.com/Nuitka/Nuitka.git && \
    cd Nuitka && \
    python setup.py install

WORKDIR /workspace
RUN python -m nuitka --module app --include-package=app && \
    mv app/main.py ./main.py && \
    python -m nuitka main.py
