# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import fastapi
import app.common.const
import PIL
import copy
import pytransform
import kakaobank_wrapper.app.utils.ocr_result_parser
import httpx
import fastapi.param_functions
import skimage.transform
import ctypes
import platform
import pydantic.networks
import pdf2image
import sqlalchemy.ext.declarative
import sqlalchemy
import re
import _frozen_importlib_external
import kakaobank_wrapper.app
import datetime
import collections
import tifffile
import sqlalchemy.sql.sqltypes
import kakaobank_wrapper.app.utils.request_parser
import json
import enum
import dataclasses
import fnmatch
import kakaobank_wrapper.app.common.const
import kakaobank_wrapper.app.utils.ocr_response_parser
import struct
import kakaobank_wrapper.app.database.connection
import functools
import typing
import fastapi.responses
import sqlalchemy.orm
import kakaobank_wrapper.app.errors
import numpy
import time
import pydantic.main
import skimage.filters
import sqlalchemy.pool
import fastapi.encoders
import loguru
import setuptools
import skimage.color
import scipy.stats
import pydantic
import logging
import sqlalchemy.engine
import starlette.middleware.base
import cv2

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...


