global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout: 1m

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["prometheus:9090"]
  # - job_name: 'textscope'
  #   scrape_interval: 15s
  #   static_configs:
  #     - targets: ['10.254.0.5:8000', '10The : indicator must be at most 1024 chars after the start of an implicit block mapping key(KEY_OVER_1024_CHARS).254.0.4:5000']
  - job_name: "general exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["textscope-hardware_telemetry:9100"]
  - job_name: "nvidia-gpu-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["textscope-gpu_telemetry:9400"]
# global:
#   slack_api_url: 'https://xxxx.com/xxxxx/slack'

# route:
#   receiver: 'slack-notifications'

#   group_by: ['alertname', 'cluster']

#   group_wait: 30s
#   group_interval: 5m
#   repeat_interval: 3h
#   routes:
#   - reveiver: 'slack-notifications'
#     group_wait: 10s
#     match_re:
#       service: mysql|cassandra

# receivers:
# - name: 'slack-norifications'
#   slack_configs:
#   - channel: 'test1'
