global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout: 1m

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['182.20.0.9:9090']
  - job_name: 'textscope'
    scrape_interval: 15s
    static_configs:
      - targets: ['182.20.0.5:8000', '182.20.0.4:5000']
  - job_name: 'general exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['182.20.0.13:9100', '182.20.0.16:9104', "182.20.0.23:9113"]
  - job_name: 'nvidia-gpu-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['182.20.0.12:9400']
  
  