---
# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: textscope-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-11.1.25
    app.kubernetes.io/instance: textscope-postgresql
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "MXEydzNlNHI="
  password: "MXEydzNlNHI="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
