replicaCount: 1

image:
  repository: docker.lomin.ai/ts-pp-base
  pullPolicy: IfNotPresent
  tag: 0.1.5
  workingDir: /workspace/pp_server/pp_server/app
  command: ["python3", "main.py"]

service:
  type: ClusterIP
  port: 80
  targetport: 8080

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

volume:
  enabled: true
  hostPath:
    enabled: true
    type: Directory
    path: /home/shinuk/Documents/gallery/Textscope
  mountPath: /workspace
  name: pp