replicaCount: 1

image:
  repository: docker.lomin.ai/ts-wrapper-base
  pullPolicy: IfNotPresent
  tag: 0.1.5

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8090

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - localhost
      secretName: tls-secret

resources: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
