replicaCount: 1

image:
  repository: docker.lomin.ai/ts-wrapper-base
  pullPolicy: IfNotPresent
  tag: 0.1.5
  workingDir: /workspace/textscope_wrapper/textscope_wrapper
  command: 
    - python3
    - main.py

service:
  type: ClusterIP
  port: 80
  targetport: 80

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - localhost
      secretName: tls-secret

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

volume:
  enabled: true
  hostPath:
    enabled: true
    type: Directory
    path: /home/shinuk/Documents/gallery/Textscope
  mountPath: /workspace
  name: wrapper