  openldap:
    container_name: ldap
    build: docker/blocks/openldap
    environment:
      SLAPD_PASSWORD: lomin
      SLAPD_DOMAIN: lomin.ai
      SLAPD_ADDITIONAL_MODULES: memberof
    ports:
      - "389:389"


