version: 2.1

orbs:
  python: circleci/python@1.0.0

jobs:
  set-bsn-code:
    machine: true
    resource_class: lomin/1
    steps:
      - run:
          name: Get pull request title
          command: |
            PR_NUMBER=$(echo $CIRCLE_PULL_REQUEST | awk -F/ '{print $7}')
            PR_TITLE=$(curl -s https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls/$PR_NUMBER | jq '.title' -r)
            echo "Pull request title is: $PR_TITLE"
            BSN_CODE=$(echo $PR_TITLE | cut -d '/' -f1)
  docker-build:
    machine: true
    resource_class: lomin/1
    steps:
      - checkout
      - run: 
          name: Setting .env file
          command: echo "$ENV_NEW" | base64 --decode > .env      
      - run:
          name: docker build
          command: |
            echo "==========> Start Docker Build";
            sh circleci/build.sh
            echo "==========> Finish Docker Build"
  docker-run:
    machine: true
    resource_class: lomin/1    
    steps:
      - run:    
          name: docker run
          command: |
            echo "==========> Start Docker Run";
            sh circleci/run.sh
            echo "==========> Finish Docker Run"                                  
  code-test:
    machine: true
    resource_class: lomin/1
    steps:
      - run:
          name: code test
          command: |
            echo "==========> Start Code Test";
            sh circleci/test.sh
            echo "==========> Finish Code Test"               

workflows:
  feature-develop-PR: 
    jobs:          
      - set-bsn-code:
          filters:
            branches:
              only: /feature\/.*/      
      - docker-build:   
          requires:
            - set-bsn-code        
          context: 
            - .env          
            - aws_new
          filters:
            branches:
              only: /feature\/.*/    
      - docker-run:
          requires:
            - docker-build   
          filters:
            branches:
              only: /feature\/.*/
      - code-test:
          requires:
            - docker-run
          filters:
            branches:
              only: /feature\/.*/            