version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6
  gh: circleci/github-cli@1.0

jobs:
  aws-cli-cred-setup:
    machine: true
    resource_class: lomin/1  
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION
  docker-build:
    machine: true
    resource_class: lomin/1
    steps:
      - checkout
      - run:
          name: docker build
          command: |
            echo "==========> Start Docker Build";
            sh circleci/build.sh
            echo "==========> Finish Docker Build"
  docker-run:
    machine: true
    resource_class: lomin/1
    steps:
      - run:    
          name: docker run
          command: |
            echo "==========> Start Docker Run";
            sh circleci/run.sh
            echo "==========> Finish Docker Run"                                  
  code-test:
    machine: true
    resource_class: lomin/1
    steps:
      - run:
          name: code test
          command: |
            echo "==========> Start Code Test";
            echo "==========> Finish Code Test"               
          # command: |
          #   echo "==========> Start Docker Run";
          #   sh run.sh
          #   echo "==========> Finish Docker Run"      
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  feature-develop-PR: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - aws-cli-cred-setup:
          context: aws        
      - docker-build:
          requires:
            - aws-cli-cred-setup       
          context:
            - .env
            - aws      
          filters:
            branches:
              only: /feature\/.*/    
      - docker-run:
          requires:
            - docker-build   
          context:
            - .env
          filters:
            branches:
              only: /feature\/.*/
      - code-test:
          requires:
            - docker-run
          filters:
            branches:
              only: /feature\/.*/            