version: 2.1

orbs:
  python: circleci/python@1.0.0

jobs:
  pip-setting:
    machine: true
    resource_class: lomin/1
    working_directory: ~/textscope
    steps:
      - run:
          name: setting pip
          command: pip install shyaml hydra-core python-dotenv alive_progress awscli
  docker-build:
    machine: true
    resource_class: lomin/1
    working_directory: ~/textscope    
    steps:
      - checkout
      - run: 
          name: Setting .env file
          command: echo "$ENV_NEW" | base64 --decode > .env      
      - run:
          name: docker build
          command: |
            echo "==========> Start Docker Build";
            sh circleci/build.sh
            echo "==========> Finish Docker Build"
  docker-run:
    machine: true
    resource_class: lomin/1
    working_directory: ~/textscope    
    steps:
      - run:    
          name: docker run
          command: |
            echo "==========> Start Docker Run";
            sh circleci/run.sh
            echo "==========> Finish Docker Run"                                  
  code-test:
    machine: true
    resource_class: lomin/1
    steps:
      - run:
          name: code test
          command: |
            echo "==========> Start Code Test";
            echo "==========> Finish Code Test"               
          # command: |
          #   echo "==========> Start Docker Run";
          #   sh run.sh
          #   echo "==========> Finish Docker Run"      
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  feature-develop-PR: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - pip-setting:    
          filters:
            branches:
              only: /feature\/.*/          
      - docker-build:   
          requires:
            - pip-setting      
          context: 
            - .env          
            - aws_new
          filters:
            branches:
              only: /feature\/.*/    
      - docker-run:
          requires:
            - docker-build   
          filters:
            branches:
              only: /feature\/.*/
      - code-test:
          requires:
            - docker-run
          filters:
            branches:
              only: /feature\/.*/            