---
# Source: minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: textscope-minio
  namespace: "default"
  labels:
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-11.2.15
    app.kubernetes.io/instance: textscope-minio
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  root-user: "dXYxTDlrdm1FdVF5cTJrY2tIM0ZBOGtRZzJKemtWSTF4anZaS0Fpc1FkMA=="
  root-password: "Sjl0bVFNRHJlOUIyYjVCSE05aEY1WURxSDhDYkJINm5FVUloWHUwMW5iSQ=="
  key.json: ""
