ARG UBUNTU_VERSION=18.04

FROM ubuntu:${UBUNTU_VERSION}

ARG BUILD_FOLDER_PATH

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PYTHONPATH="$PYTHONPATH:/workspace"
ENV API_ENV="production"

RUN apt-get update && \
    apt-get install -y locales && \
    locale-gen ko_KR.UTF-8 && \
    apt-get -y install python3-pip && \
    apt-get -y install libmysqlclient-dev

RUN pip3 install --upgrade pip

COPY ./requirments/requirments-web.txt /workspace/
RUN pip3 install -r /workspace/requirments-web.txt

COPY ./${BUILD_FOLDER_PATH}/web/ /workspace/
COPY ./.env /workspace/

RUN rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache

WORKDIR /workspace

# ENTRYPOINT ["python3", "main.py"]