ARG UBUNTU_VERSION=18.04

FROM ubuntu:${UBUNTU_VERSION} as builder

ARG BASE_PATH
ARG LINUX_ENV_PATH
ARG DEMOMA_PATH
ARG SO_EXTENTION

ENV PYTHONPATH="$PYTHONPATH:/workspace"

RUN apt-get update && \
    apt-get -y install git && \
    apt-get -y install python3-pip && \
    apt-get -y install libmysqlclient-dev

COPY ./app /workspace/app
COPY ./assets/thales/ /workspace/assets/thales
COPY ./.env /workspace/.env     
COPY ./requirments/requirments-web.txt /workspace/requirments-web.txt

RUN pip3 install --upgrade pip && \
    pip3 install -r /workspace/requirments-web.txt

WORKDIR /workspace
RUN git clone https://github.com/Nuitka/Nuitka.git && \
    cd Nuitka && \
    python3 setup.py install

RUN mv app/main.py ./main.py && \
    python3 -m nuitka --module app --include-package=app && \
    ${LINUX_ENV_PATH} -v:${DEMOMA_PATH} -f:100 --dfp app.${SO_EXTENTION} app.${SO_EXTENTION}

# RUN rm -r /workspace/app /workspace/*.build /workspace/*.txt /workspace/Nuitka /workspace/assets && \
#     rm -rf /var/lib/apt/lists/*

FROM ubuntu:${UBUNTU_VERSION}

ENV PYTHONPATH="$PYTHONPATH:/workspace"

RUN apt-get update && \
    apt-get -y install python3-pip && \
    apt-get -y install libmysqlclient-dev

COPY --from=builder /workspace/.env /workspace/
COPY --from=builder /workspace/requirments-web.txt /workspace/
COPY --from=builder /workspace/app.cpython-36m-x86_64-linux-gnu.so /workspace/
COPY --from=builder /workspace/app.pyi /workspace/
COPY --from=builder /workspace/main.py /workspace/

RUN pip3 install --upgrade pip && \
    pip3 install -r /workspace/requirments-web.txt

RUN rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache

# ENTRYPOINT ["python3", "main.py"]

# ARG BASE_PATH="/workspace"
# ARG LINUX_ENV_PATH="/workspace/assets/thales/linuxenv"
# ARG DEMOMA_PATH="/workspace/assets/thales/DEMOMA.hvc"
# ARG SO_EXTENTION="cpython-36m-x86_64-linux-gnu.so"
