ARG UBUNTU_VERSION=18.04

FROM ubuntu:${UBUNTU_VERSION}

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PYTHONPATH="$PYTHONPATH:/workspace"

RUN apt-get update && \
    apt-get -y install python3-pip && \
    apt-get -y install libmysqlclient-dev

COPY --from=builder /workspace/.env /workspace/
COPY --from=builder /workspace/requirments-web.txt /workspace/
COPY --from=builder /workspace/app.cpython-36m-x86_64-linux-gnu.so /workspace/
COPY --from=builder /workspace/app.pyi /workspace/
COPY --from=builder /workspace/main.py /workspace/

RUN pip3 install --upgrade pip && \
    pip3 install -r /workspace/requirments-web.txt

RUN rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache

# ENTRYPOINT ["python3", "main.py"]