replicaCount: 1

image:
  repository: docker.lomin.ai/ts-pp
  pullPolicy: Never
  tag: 0.6.0
  workingDir: /workspace/pp_server
  command: ["python3", "main.py"]

service:
  type: ClusterIP
  port: 8080
  targetport: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

volume:
  enabled: true
  hostPath:
    enabled: true
    type: DirectoryOrCreate
    path: /home/inhak/log
  mountPath: /workspace/logs
  name: log

env:
  enabled: true
  normal:
    PYTHONPATH: /workspace