version: "3.8"

services:
  nginx:
    container_name: textscope-plugin-webview
    image: docker.lomin.ai/ts-plugin-webview:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NGINX_FILE_DEFAULT: default.conf
        NGINX_FILE_NGINX: nginx.conf
    environment:
      - PYTHONPATH=/workspace
      - TZ=Asia/Seoul
    volumes:
      - ./:/workspace
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:8090
      - 2222:22
    tty: true
    # entrypoint: /bin/bash
    restart: always
    networks:
      - our_net

networks:
  our_net:
    name: our_net
    ipam:
      config:
        - subnet: 10.254.0.0/16

